name: build.yml
on:
    push:
        branches:
            - v2
    pull_request:
        branches:
            - v2

jobs:
    build:
        runs-on: ubuntu-latest
        name: 🏗️ Build
        strategy:
            matrix:
                config:
                    - uzl
                    - cau
        steps:
            - name: 📥️ checkout
              uses: actions/checkout@v4

            - name: 🎛️ setup
              uses: ./.github/actions/setup

            - name: 🏗️ build Better-Moodle for ${{ matrix.config }}
              run: yarn build ${{ matrix.config }}

            - name: 📤️ upload build
              uses: actions/upload-artifact@v4
              with:
                  name: better-moodle-${{ matrix.config }}.user.js
                  path: dist/better-moodle-${{ matrix.config }}.user.js

            # TODO: Output build stats
