name: build.yml
on:
    push:
        branches:
            - v2
    pull_request:
        branches:
            - v2

jobs:
    build:
        runs-on: ubuntu-latest
        name: 🏗️ Build
        strategy:
            matrix:
                config:
                    - uzl
                    - cau
        env:
            dist_dir: dist
            dist_file: better-moodle-${{ matrix.config }}.user.js
        steps:
            - name: 📥️ checkout
              uses: actions/checkout@v4

            - name: 🎛️ setup
              uses: ./.github/actions/setup

            - name: 🏗️ build Better-Moodle for ${{ matrix.config }}
              run: yarn build ${{ matrix.config }}

            - name: 📤️ upload build
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.dist_file }}
                  path: ${{ env.dist_dir }}/${{ env.dist_file }}

            - name: 📊 aggregate build statistics
              run: |
                  echo "STATS_SIZE=$(ls -sh --si '${{ env.dist_dir }}/${{ env.dist_file }}' | awk '{print $1}')B" >> $GITHUB_ENV
                  echo "STATS_LINES=$(wc -l '${{ env.dist_dir }}/${{ env.dist_file }}' | awk '{print $1}')" >> $GITHUB_ENV

            # TODO: Output build stats
            - name: ✍️ print build stats in summary
              run: |
                  echo "# 🏗️ ${{ matrix.config }}" >> $GITHUB_STEP_SUMMARY
                  echo "## Built file: \`${{ env.dist_file }}\`" >> $GITHUB_STEP_SUMMARY
                  echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
                  echo "|-------:|:------|" >> $GITHUB_STEP_SUMMARY
                  echo "| **File size** | ${{ env.STATS_SIZE }} |" >> $GITHUB_STEP_SUMMARY
                  echo "| **Line count** | ${{ env.STATS_LINES }} |" >> $GITHUB_STEP_SUMMARY
