name: build.yml
on:
    push:
        branches:
            - v2
    pull_request:
        branches:
            - v2

jobs:
    setup:
        name: 🎛️ Setup
        uses: ./.github/workflows/_setup.yml

    build:
        needs: [setup]
        runs-on: ubuntu-latest
        name: 🏗️ Build
        steps:
            - name: 🏗️ build Better-Moodle for UzL
              run: yarn build uzl

            # TODO: Run not only UzL but also other configs?
