on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  config-file: .release-please-config.json
                  manifest-file: .release-please-manifest.json
        outputs:
            released: ${{ steps.release.outputs.release_created }}
            tag: ${{ steps.release.outputs.tag_name }}

    assets:
        runs-on: ubuntu-latest
        needs: release
        if: ${{ needs.release.outputs.released }}
        strategy:
            matrix:
                config:
                    - uzl
                    - cau
        steps:
            - name: Build
              id: build
              uses: ./.github/actions/build
              with:
                  config: ${{ matrix.config }}

            - name: Upload release artifacts
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # get meta filename
                  file="${{ steps.build.output.file }}"
                  meta=$(sed 's/\.user\.js/\.meta\.user\.js/' <<< "$file")

                  # extract metadata/userscript-header from the user script
                  awk '/\/\/ ==UserScript==/,/\/\/ ==\/UserScript==/' "${{ steps.build.output.dir }}/$file" > "${{ steps.build.output.dir }}/$meta"

                  # upload the release artifacts with special nice names
                  gh release upload ${{ needs.release.outputs.tag }} \
                    "${{ steps.build.output.dir }}/$file#[${{ matrix.config }}] Better-Moodle userscript version ${{ steps.release.outputs.tag_name }} ($file)" \
                    "${{ steps.build.output.dir }}/$meta#[${{ matrix.config }}] Better-Moodle meta file for userscript managers ($meta)"
