name: '[🧑‍🍳] Update Speiseplan'

on:
    schedule:
        - cron: '0 * * * *' # Run once every hour
    workflow_dispatch: # Allow manual runs

jobs:
    crawl:
        name: '[🍲] Update Speiseplan'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js LTS
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
            - name: Setup yarn
              run: |
                  corepack enable
                  yarn set version latest
            - name: Install dependencies
              run: |
                  yarn install --immutable
            - name: '[🥗] The real Speiseplan update step'
              run: node ./speiseplan/getSpeiseplan.js
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  message: |
                      chore(speiseplan): update to latest speiseplan

                      Hmm that all looks pretty yummy! 😋
